import type { Metadata } from "next";
import { SeoPage } from "@/components/marketing/SeoPage";

export const metadata: Metadata = {
  title: "Bankroll Management Guide",
  description:
    "Learn the fundamentals of bankroll management, session tracking, limits, variance and performance analysis.",
  alternates: { canonical: "/bankroll-management-guide" },
};

const sections = [
  {
    title: "What is bankroll management?",
    paragraphs: [
      "Bankroll management is the process of separating playing funds from everyday money and choosing stakes that limit the risk of ruin. It applies to poker, sports betting and casino play.",
      "A bankroll is not the same as profit. Deposits increase the available balance, withdrawals reduce it and completed sessions create wins or losses. Tracking these movements separately keeps your results honest.",
    ],
  },
  {
    title: "Build a repeatable tracking routine",
    paragraphs: [
      "Record a session as soon as it begins and complete it immediately after play. Consistent timestamps, buy-ins, cash-outs and notes produce more useful statistics than occasional summaries.",
      "Review performance over meaningful samples. One winning day does not prove an edge, and one losing week does not automatically mean a strategy is failing.",
    ],
    bullets: [
      "Set a dedicated bankroll before playing",
      "Define personal stake and loss limits",
      "Track every session without exceptions",
      "Review profit, ROI, volume and hourly rate together",
      "Move down in stakes when your limits require it",
    ],
  },
  {
    title: "Understand variance and responsible limits",
    paragraphs: [
      "Short-term results contain variance. Even sound decisions can lose, while poor decisions can win temporarily. A larger data history makes trends easier to evaluate without overreacting.",
      "Bankroll management does not make gambling risk-free. Never chase losses, borrow money to play or use funds needed for housing, bills or other essentials. Stop when play is no longer controlled or enjoyable.",
    ],
  },
  {
    title: "Use data to improve decisions",
    paragraphs: [
      "Compare results by game type, platform and time period. Look for patterns supported by enough sessions rather than selecting only your best outcomes.",
      "Bankrollary calculates key metrics automatically and keeps deposits and withdrawals separate, giving you a clearer foundation for reviewing your activity.",
    ],
  },
];

const faq = [
  {
    question: "How large should a bankroll be?",
    answer:
      "There is no universal amount. It depends on the game, stakes, variance, personal risk tolerance and whether the bankroll can be replenished.",
  },
  {
    question: "Are deposits counted as profit?",
    answer:
      "No. Deposits change the available bankroll but should remain separate from profit generated by completed sessions.",
  },
  {
    question: "How often should I review results?",
    answer:
      "Record every session and review periodically, such as weekly or monthly. Avoid making major decisions from only a few results.",
  },
  {
    question: "Does bankroll management guarantee profit?",
    answer:
      "No. It controls exposure and improves record keeping, but it cannot guarantee wins or remove gambling risk.",
  },
];

export default function BankrollManagementGuidePage() {
  return (
    <SeoPage
      eyebrow="Practical bankroll guide"
      title="Bankroll Management Guide"
      description="Learn how to separate funds, track every session, understand variance and review your bankroll without confusing deposits with profit."
      sections={sections}
      faq={faq}
    />
  );
}
